export const AUTH_CREATE_USER = 'AUTH_CREATE_USER';
export const AUTH_UPDATE_SIGNUP_FORM = 'AUTH_UPDATE_SIGNUP_FORM';
export const AUTH_RESET_SIGNUP_FORM = 'AUTH_RESET_SIGNUP_FORM';
export const AUTH_SET_FORM_VALIDATION_ERRORS = 'AUTH_SET_FORM_VALIDATION_ERRORS';
export const AUTH_UPDATE_SIGNIN_FORM = 'AUTH_UPDATE_SIGNIN_FORM';
export const AUTH_SET_CURRENT_USER = 'AUTH_SET_CURRENT_USER';
